- notebooks/custom_plot.json
- notebooks/prenight.ipynb
- schedview/app/prenight/prenight.py
- schedview/compute/astro.py
- schedview/data/sample_prenight_custom_hvplots.json
- schedview/data/test_prenight_custom_hvplots.json
- tests/test_prenight.py
These changes should also close PREOPS-3600.
> PREOPS-3639: support setting custom prenight tabs from a file specified on the command line

- .github/workflows/build_pypi.yaml
The change to avoid rs_download_data in build_pypi did not actually get checked in the first time.
> avoid rs_download_data

- pyproject.toml
This reverts commit 12de4509eabe43767f6a3998075ae564669bbc34, which took out rubin_sim as a dependency.
> Revert "remove rubin_sim as a schedview dependency"

- schedview/app/scheduler_dashboard/scheduler_dashboard.py
- Pass newly added conditions and survey parameters to schedview.plot.survey.map_survey_healpix()
- Update Bokeh plot of key to match colour and alpha values of plot objects.
> PREOPS-3752: Add survey fields and telescope pointing to map.

- schedview/app/scheduler_dashboard/scheduler_dashboard.py
- tests/test_scheduler_dashboard.py
This PR allows the scheduler dashboard to accept scheduler file name, nside and date mjd value as url paramaters.
- use `scheduler` to set scheduler file name (path or URL)
- use `nside` to set nside value
- use `mjd` to set date/time in mjd format
Example:
`http://localhost:8080?nside=16&scheduler=%2Fhome%2Feman%2FDownloads%2Fsched_maps%2Fexample_pickle_scheduler.p.xz&mjd=60207`
> accept nside, scheduler file name and mjd as url parameters

- schedview/app/scheduler_dashboard/scheduler_dashboard.py
- tests/test_scheduler_dashboard.py
Survey number is now pulled from the scheduler summary row number, instead of the survey name.
The test_title unit test has been updated in line with this change.
> Tickets/PREOPS-4105: Change how survey number is queried in subtitle.

- schedview/app/scheduler_dashboard/scheduler_dashboard.py
Define nside values as int list rather than np.int64 array to make th…e sync between with the nside URL parameter seamless
> PREOPS-4512 Serialization error when choosing nside value from the dropdown

- schedview/app/scheduler_dashboard/scheduler_dashboard.py
- schedview/compute/scheduler.py
- Index fields added to df output by make_scheduler_summary_df() to maintain integer ordering.
- Index column added to scheduler summary table.
- Additionally, survey_name field changed to avoid overloading.
> Tickets/PREOPS-4401: Rewards table displays data for the wrong survey.

- schedview/app/scheduler_dashboard/scheduler_dashboard.py
- tests/test_scheduler_dashboard.py
- Set date from the conditions object of a loaded pickle file.
- Simplify date-related functions to manage pickle, url and widget date inputs.
- Modify attribute names to remove confusion.
> Tickets/PREOPS-4400: Date does not update correctly.

- schedview/compute/scheduler.py
The documentation links in the top table in scheduler_dashboard were broken because of this bug. This should fix these links, where possible.
> tickets/PREOPS-4526: fix survey class URLs

- schedview/plot/nightly.py
Erik gave me a push on this this morning, so I pushed it to the top of my to do list.
> tickets/PREOPS-4597: color by note in schedview prenight az/alt plt

- Dockerfile
- container_environment.yaml
- schedview/app/scheduler_dashboard/scheduler_dashboard.py
The k8 ingress seems to have trouble getting supplying bokeh js libraries unless the dashboard is served a couple of directories "down" in the url, that is https://myhost/a/b works, but https://myhost and https://myhost/a do not.
There might be a way either to get bokeh to serve its libraries differently or get the ingress to handle routing to the js libraries, but I couldn't find it, and just moving the URL is easy and has no downsides that I can see.
I named the dir "scheduler-snapshot" here to make it clear how it is different from other existing planned or existing schedview dashboards, which can also be thought of as scheduler-related dashboards. What makes this dashboard distinctive is that it looks at the state of the scheduler as captured (in a pickle, at least for now) at a given …
> tickets/PREOPS-4603: prepare schedview's scheduler_dashboard app for running at USDF w/ k8

- .github/workflows/build_container.yaml
- .github/workflows/test_and_build.yaml
- container_environment.yaml
- environment.yaml
- pyproject.toml
- requirements.txt
- schedview/app/prenight/prenight.py
- schedview/collect/opsim.py
- schedview/collect/resources.py
- tests/test_resources.py
Right now, it's only been tested on files in the local filesystem and package resources, but hopefully it will work with s3 buckets as well, when there is one with opsim data.
> tickets/PREOPS-4685: use lsst.resources for loading data in the prenight briefing

- schedview/app/scheduler_dashboard/scheduler_dashboard.py
- schedview/plot/survey.py
- The static key has been removed.
- The plot objects have had kwargs added that allow the objects to be displayed nicely in the plot's native key.
- The order in which plot objects are added has been rearranged to display key objects in a nice order.
- The layout around the plot has been modified to allow for the new plot-attached key.
- Colours of plot line objects (ecliptic, galactic plane, etc.) have been modified for greater accessibility, with colours derived from a colourblind-accessible colour palette.
> PREOPS-4817: Integrate key and map with colourblind-friendly plot elements.

- schedview/app/scheduler_dashboard/scheduler_dashboard.py
Add a button to reload a pickle file to restore original loading condition
> PREOPS-4832 Add a button to reset dashboard to initial load conditions

- schedview/app/scheduler_dashboard/scheduler_dashboard.py
- tests/test_scheduler_dashboard.py
Get the date range covered by SkyBrightness_Pre data files and limit date picker to this range so that user cannot select outside the values that have data
> PREOPS-4838 Limiting the datetime selector’s range to those for which there are sky brightness files

- schedview/app/scheduler_dashboard/scheduler_dashboard.py
Survey table:
- Decouple the documentation links from the survey names.
- Remove ability to sort by the doc links column.
Reward table:
- Decouple the documentation links from the basis function names.
- Add an accumulation order index column so original ordering can be restored if manually changed.
- Add units (square degrees) to the area columns.
- Set the number of decimal places to be displayed for each column.
- Change layout setting so column widths are updated to match data widths.
- Remove ability to sort by doc links and feasible columns.
> PREOPS-4870: Apply UX testing recommendations to tables.

- schedview/app/scheduler_dashboard/scheduler_dashboard.py
Changes addressing identified issues include:
- Map heading now consistent across basis function selection by row selection or drop-down.
- Upper bound of date range decreased by 0.01 MJD (~15 mins) to prevent error at upper bound.
- Reset nside and colour palette to defaults when reset button clicked.
Additional aesthetic and code layout changes include:
- Reset button moved up slightly to fill gap.
- Hover description added to reset button and icon slightly increased in size.
- Function called on button click moved out of layout code section.
> PREOPS-4934: Fix minor issues found during end-to-end testing.

- .github/workflows/cache.yaml
Last update didn't include installing rubin-sim so as a result cache workflow didn't know about rs_download_data. now it does.
> install rubin-sim to get rubin-sim's data download too

- schedview/compute/scheduler.py
The `"note" in survey.observations` syntax doesn't work when survey.observations is a `numpy.recarray`, but it can be such in the new auxtel scheduler, and schedview really aught to handle this correctly. Using a try/except block lets schedview be more versatile. This is another instance of "better to ask forgiveness" being better than "look before you leap" in python.
> tickets/PREOPS-4896: make schedview's make_unique_survey_name more robust w.r.t. survey.observations type

- docs/installation.rst
- schedview/collect/opsim.py
- schedview/compute/__init__.py
- schedview/compute/maf.py
- schedview/compute/visits.py
- tests/test_compute_maf.py
- tests/test_compute_visits.py
- tests/test_plot_cadence.py
This PR also include changes for PREOPS-4990, which let the scheduler snapshot dashboard run without rubin_sim installed.
> tickets/PREOPS-4949: Move computations of some visit params to rubin_sim stackers

- schedview/plot/__init__.py
- schedview/plot/nightly.py
- schedview/plot/rewards.py
- tests/test_plot_rewards.py
Needed to support adding such plots to the Times Square pre-night briefing.
> tickects/PREOPS-5067: Add basis function and survey rewards timeline plots that do not use python callbacks

- docs/installation.rst
- test-requirements.txt
The S3 bucket has dependencies not installed by the existing instructions, and schedview no longer needs special credentials to read from the bucket.
(I also included the playwright install as well, even though the branch that needs it hasn't been merged yet.)
> tickets/PREOPS-5235: update install instructions

- schedview/plot/overhead.py
- schedview/plot/visits.py
bokeh.plotting.figure.circle is sometimes throwing deprecation warnings, and sometimes silently just not plotting points (with the latest version of bokeh).
> PREOPS-5239: Switch schedview from using bokeh.plotting.figure.circle to bokeh.plotting.figure.scatter with marker=circle

- schedview/collect/consdb.py
- tests/test_consdb.py
This will only work after the merge of a corresponding PR in rubin_scheduler.
> tickets/PREOPS-5245: Add support for reading visits from ConsDB

- tests/test_multisim.py
adding test that was supposed to be included in the original merge or tickets/PREOPS-4640, but got missed.
> tickets/PREOPS-4640a: test result of match_visits_across_sims when there are no matches

- schedview/app/scheduler_dashboard/scheduler_dashboard_app.py
- schedview/app/scheduler_dashboard/unrestricted_scheduler_snapshot_dashboard.py
To highlight which survey is "chosen" for a particular snapshot, a dynamic label has been created with the text "Chosen survey is ... ". This label is updated to display the "chosen" tier and survey whenever a new snapshot is loaded.
The label sits above the Scheduler Summary table header on a dark teal background.
> tickets/PREOPS-5539: Highlight winning survey on snapshot dashboard

- schedview/__init__.py
- schedview/collect/__init__.py
- schedview/collect/consdb.py
- schedview/collect/visits.py
- schedview/dayobs.py
- schedview/plot/survey.py
- tests/test_dayobs.py
Add wrapper code that can figure out how to load what the user asks for, whether it is a sim or data from an instrument in consdb.
> tickets/SP-1667: Merge the Times Square OR4 nightsum with the nightly nightsum

- schedview/compute/scheduler.py
Look at the comment on line 262 for an explanation of where this came from to begin with.
> ticktes/SP-1735: use scheduler name when possible

- schedview/collect/efd.py
- schedview/collect/timeline.py
- schedview/compute/astro.py
- schedview/compute/efd.py
- schedview/compute/obsblocks.py
- schedview/examples/app/combined_timeline.py
- schedview/examples/timeline.py
- schedview/plot/__init__.py
- schedview/plot/timeline.py
- tests/test_nightreport.py
- tests/test_plot_rewards.py
- tests/test_timeline.py
This PR is for the initial infrastructure and a few initial examples.
I expect plots to be supplemented and refined in additional issues and PRs.
> tickets/SP-1789: plot EFD logevents on an event timeline plot

- schedview/collect/opsim.py
The constraint for read_ddf_visits used "target" (old column name) instead of "target_name" (new column name). 
Many other uses of opsim are backward compatible, but it's not obvious how to make this particular use backward compatible unless you retrieve all visits and then sub-select afterwards, or query table first to check for columns .. essentially doing the work that is done in the next step of "read_opsim", and I didn't want to duplicate code.
> SP-1864: Swap target to target_name in DDF constraint

- schedview/collect/consdb.py
This applies the mechanism for clinet-site-dependent endpoints to consdb queries.
> tickets/SP-2177: Use clientsite to get consdb endpoint

- container_environment.yaml
Presently running the snapshot dashboard on usdf-int, seems to work even though the scheduler running at the observatory is still 3.7.0.
> Update rubin_scheduler dependency in schedview container to 3.8.0

- .pre-commit-config.yaml
- schedview/plot/overhead.py
- schedview/plot/survey_skyproj.py
- schedview/reports.py
- tests/test_reports.py
The initial table of contents is in the schedview_notebooks notebook itself (in the PR for tickets/SP-2213), but it should be someplace reusable and testable, so here it is.
> tickets/SP-2352: add code to build a table of contents for pre-generate schedview reports (plus rss, which is almost the same)

- container_environment.yaml
- pyproject.toml
- requirements.txt
- schedview/collect/visits.py
This updates the requirements.txt and the pyproject.toml to the minimum required versions of rubin-sim and rubin-scheduler.
I did a bad PR, but also added a slight modification to read_visits so that you can read not-just the baseline or a version # (but also, say, the sv survey simulation output). Eric and Lynne discussed this over the weekend.
> SP-2370: Update required version of rubin_scheduler and rubin_sim

- schedview/plot/cadence.py
Just turn on the bokeh option to do it.
> tickets/SP-2229: Prevent overlap of date tick labels in DDF cadence plot

- schedview/collect/sv.py
- schedview/collect/visits.py
The implementation here is short term, until we address SP-2442.
It requires the merge of tickets/SP-2444 on rubin_scheduler.
> tickets/SP-2444: Simplified API for querying sv visits from the consdb

- schedview/reports.py
The public table of contents does not have the some reports as the private one, so the TOC creation code needs to be more flexible.
> tickets/SP-2470: Suport setting which reports to include in the report TOC
