notebooks/prenight.ipynb, pyproject.toml, schedview/app/prenight/prenight.py, schedview/collect/opsim.py, schedview/plot/nightly.py, tests/test_nightly.py
This merge request includes both tickets, and replaces the previous 3616 merge request.
=> Tickets/preops 3616 and Tickets/preops 3513: add airmass vs. time and horizon coordinates plots to prenight

notebooks/prenight.ipynb, notebooks/prenight_matplotlib_extension.ipynb, notebooks/prenight_multielement_extension.ipynb, schedview/app/prenight/prenight.py, schedview/plot/nightbf.py, schedview/plot/rewards.py
I minor change to the prenight python class to make addition of tabs through subclassing simpler, plus some notebooks with examples of how to do it.
=> Tickets/preops 3640: Refactor the prenight briefing to make it easier to customize through subclassing

schedview/app/prenight/prenight.py, schedview/plot/visitmap.py
The first of a few optimizations
=> PREOPS-3732:  only load 1 night of pre-computed sky brightness

pyproject.toml
This should quiet the conda bot
=> tickets/PREOPS-3849: remove unnecessary dependencies, and add param explicitly

schedview/app/prenight/prenight.py
Adds a --show option to `prenight` which causes it to show the dashboard in a new browser window.
=> tickets/PREOPS-3843: add --show option to prenight

schedview/app/prenight/prenight.py
This is at the point where it starts, and can look at the data file contained within the package.
=> tickets/PREOPS-4565 Modify schedview-prenight dashboard startup to support running within k8

pyproject.toml, requirements.txt
This should go in (and tag schedview) before merging PREOPS-4607
=> Pin rubin-sim to <2 for this version of schedview

schedview/app/prenight/prenight.py
=> tickets/PREOPS-4099: add a reload button to the prenight dashboard

schedview/app/scheduler_dashboard/scheduler_dashboard.py
Remove pagination in both tables
set table height to enable scrolling
remove basis function class column
introduce column widths in basis function table
fix logo url
=> PREOPS-4906 - Use scrolling rather than pagination to show overflowing content in rewards and basis function tables

schedview/app/scheduler_dashboard/scheduler_dashboard.py
Improve logging within the dashboard’s custom debugging panel and also in stderr.
- Add more logging messages throughout code.
- Send logging information to stderr (as well as dashboard debugging panel) using Python’s inbuilt logger module.
- Prevent debugging messages from spilling outside debugger area.
- Improve formatting of dashboard debugger.
=> PREOPS-4935: Improve logging

schedview/app/scheduler_dashboard/scheduler_dashboard.py
Responses to feedback since making the post-user testing version available at the USDF.
=> tweaks to text in the scheduler snapshot dashboard UI

.github/workflows/cache.yaml
Only updates the build_cache.yaml workflow
=> typo in cache building yaml

schedview/plot/visitmap.py
Because of course my last PR had a bug in it. Ugh.
=> tickets/PREOPS-5294: let plot_visit_skymaps work however the visits DF is indexed.

docs/index.rst, docs/prenight_sim_generation.rst
=> tickets/SP-1984: Add section on automatic pre-night simulation generation

Dockerfile, schedview/app/scheduler_config_at_time.py, schedview/collect/efd.py, schedview/collect/multisim.py, schedview/collect/nightreport.py, schedview/collect/visits.py, schedview/compute/__init__.py, schedview/compute/sim_archive.py, schedview/examples/app/combined_timeline.py, schedview/examples/ddfcadence.py, schedview/plot/__init__.py, schedview/plot/sim_archive.py, tests/test_sim_archive.py
~~This branch is itself a branch of the tickets/SP-2005 branch, so merging it will merge that branch as well. It depends on the tickets/SP-2165 changes in rubin_sim.~~ (tickets/SP-2005 has been merged onto main)
=> tickets/SP-2165: Set up automatic pre-night opsim simulations for lsstcam

schedview/plot/survey_skyproj.py
Fixes issue with skyproj that is preventing accumulated depth from showing up in the nightsim
=> SP-2309: specify now-required extent argument is skyproj.LaeaSkyproj

schedview/plot/visitmap.py
add science_program and observation_reason to hovertext on the scheduler-nightsum visit map
=> tickets/SP-2312: add science_program and observation_reason to hovertext on the scheduler-nightsum visit map

schedview/plot/survey_skyproj.py
A bug slipped through in one of the just merged PRs. Here is the fix.
=> tickets/SP-2473: actually use passed axes in map_visits_over_healpix

schedview/collect/auth.py, schedview/collect/multisim.py
This branch is off the end of tickets/SP-2539.
=> tickets/SP-2544: Be robust to metadata data missing from the prenight sim database

schedview/plot/visits.py
I think this isn't absolutely necessary at this point, given that you can do this:
```
tooltips = 'mynewMJD: @observationStartMJD{00000.00}'
fig = schedview.plot.plot_visit_param_vs_time(visits, 'airmass', hovertool=False, show_column_selector=True, name="timelinerenderer")
timeline = next(fig.select({'name': 'timelinerenderer'}))
hover_tool = bokeh.models.HoverTool(renderers=[timeline], tooltips=tooltips)
scatterplot = fig.children[1]
scatterplot.add_tools(hover_tool)
bokeh.io.show(fig)
```
but these changes should provide alternate avenues that should be more straightforward to figure out.
Note that this PR includes three separate ways of doing it (module-level variables, an added argument, and a name for the renderer), but none really make the code harder to maintain or understand, I …
=> tickets/SP-2479: Make it easier to customize tooltips in the visits timeline plot

schedview/compute/visits.py, schedview/plot/__init__.py, schedview/plot/overhead.py, tests/test_sv_summary.py
=> add basic sv stat table
